pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                bat 'cd BankManager && mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'cd BankManager && mvn test'
            }
        }

        stage('Package') {
            steps {
                bat 'cd BankManager && mvn package -DskipTests'
            }
        }
    }
}